// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatiKrab.Data;

#nullable disable

namespace PlatiKrab.Data.Migrations
{
    [DbContext(typeof(PlatiKrabDbContext))]
    [Migration("20250206181507_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("PlatiKrab.Data.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Paid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerWhoPaysPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PaymentId");

                    b.HasIndex("PlayerWhoPaysPlayerId");

                    b.HasIndex("TrainingId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PlatiKrab.Data.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("PlatiKrab.Data.Models.PlayerTraining", b =>
                {
                    b.Property<int>("PlayerTrainingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerTrainingId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TrainingId");

                    b.ToTable("PlayerTrainings");
                });

            modelBuilder.Entity("PlatiKrab.Data.Models.Training", b =>
                {
                    b.Property<int>("TrainingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("TrainingId");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("PlatiKrab.Data.Models.Payment", b =>
                {
                    b.HasOne("PlatiKrab.Data.Models.Player", "PlayerWhoPays")
                        .WithMany("Payments")
                        .HasForeignKey("PlayerWhoPaysPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlatiKrab.Data.Models.Training", "Training")
                        .WithOne("Payment")
                        .HasForeignKey("PlatiKrab.Data.Models.Payment", "TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerWhoPays");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("PlatiKrab.Data.Models.PlayerTraining", b =>
                {
                    b.HasOne("PlatiKrab.Data.Models.Player", "Player")
                        .WithMany("PlayerTrainings")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlatiKrab.Data.Models.Training", "Training")
                        .WithMany("PlayerTrainings")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("PlatiKrab.Data.Models.Player", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("PlayerTrainings");
                });

            modelBuilder.Entity("PlatiKrab.Data.Models.Training", b =>
                {
                    b.Navigation("Payment");

                    b.Navigation("PlayerTrainings");
                });
#pragma warning restore 612, 618
        }
    }
}
