// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatiKrab.Data;

#nullable disable

namespace PlatiKrab.Data.Migrations
{
    [DbContext(typeof(PlatiKrabDbContext))]
    [Migration("20250204083805_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("PlatiKrab.Data.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerWhoPaysId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerWhoPaysId");

                    b.HasIndex("TrainingId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PlatiKrab.Data.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("PlatiKrab.Data.Models.PlayerTraining", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TrainingId");

                    b.ToTable("PlayerTrainings");
                });

            modelBuilder.Entity("PlatiKrab.Data.Models.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("PlatiKrab.Data.Models.Payment", b =>
                {
                    b.HasOne("PlatiKrab.Data.Models.Player", "PlayerWhoPays")
                        .WithMany()
                        .HasForeignKey("PlayerWhoPaysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlatiKrab.Data.Models.Training", "Training")
                        .WithOne("Payment")
                        .HasForeignKey("PlatiKrab.Data.Models.Payment", "TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerWhoPays");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("PlatiKrab.Data.Models.PlayerTraining", b =>
                {
                    b.HasOne("PlatiKrab.Data.Models.Player", "Player")
                        .WithMany("Trainings")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlatiKrab.Data.Models.Training", "Training")
                        .WithMany("Players")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("PlatiKrab.Data.Models.Player", b =>
                {
                    b.Navigation("Trainings");
                });

            modelBuilder.Entity("PlatiKrab.Data.Models.Training", b =>
                {
                    b.Navigation("Payment")
                        .IsRequired();

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
