// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatiKrab.Data;

#nullable disable

namespace PlatiKrab.Data.Migrations
{
    [DbContext(typeof(PlatiKrabDbContext))]
    partial class PlatiKrabDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("PlatiKrab.Data.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Paid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PaymentId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TrainingId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PlatiKrab.Data.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("PlatiKrab.Data.Models.Training", b =>
                {
                    b.Property<int>("TrainingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("TrainingId");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("PlatiKrab.Data.Models.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DarkMode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("PlayerTraining", b =>
                {
                    b.Property<int>("PlayersPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainingsTrainingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayersPlayerId", "TrainingsTrainingId");

                    b.HasIndex("TrainingsTrainingId");

                    b.ToTable("PlayerTraining");
                });

            modelBuilder.Entity("PlatiKrab.Data.Models.Payment", b =>
                {
                    b.HasOne("PlatiKrab.Data.Models.Player", "Player")
                        .WithMany("Payments")
                        .HasForeignKey("PlayerId");

                    b.HasOne("PlatiKrab.Data.Models.Training", "Training")
                        .WithOne("Payment")
                        .HasForeignKey("PlatiKrab.Data.Models.Payment", "TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("PlayerTraining", b =>
                {
                    b.HasOne("PlatiKrab.Data.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayersPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlatiKrab.Data.Models.Training", null)
                        .WithMany()
                        .HasForeignKey("TrainingsTrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlatiKrab.Data.Models.Player", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("PlatiKrab.Data.Models.Training", b =>
                {
                    b.Navigation("Payment");
                });
#pragma warning restore 612, 618
        }
    }
}
